client-react:
  image: react-docker
  command: redis-server --appendonly yes
  volumes:
  - /root/rss2twitter/data:/data
  ports:
  - "6379:6379"

server-express:
  image: express-docker
  build: app
  links:
  - redis

database-mongodb:
  image: mongodb-docker