version: '3'

services:
  database-mongodb:
    build:
      context: ./database
    ports: 
      - "27017:27017"
    restart: always
    volumes:
      - /usr/local/mongodb/gitetantejeanne:/data/db
  
  server-express:
    build:
      context: ./server
    ports: 
      - "3000:3000"
    links:
      - database-mongodb:db
    depends_on:
      - database-mongodb
    restart: always

  client-react:
    build:
      context: ./client
    ports:
      - "80:80"
    links:
      - server-express:server
