version: '2'
services:
  database-mongodb:
    build:
      context: ./database
    ports: 
      - "27017:27017"
  
  server-express:
    build:
      context: ./server
    ports: 
      - "3000:3000"
    links:
      - database-mongodb:db

  client-react:
    build:
      context: ./client
    ports: 
      - "80:80"
    links:
      - server-express:server
